<?php
/**
 * Copyright (C) 2016 Webformat S.r.l.
 * http://www.webformat.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php
/**
 * @see Webformat_ViewedProducts_Block_Customer_Products_List
 */
?>
<?php $_items = $this->getItems(); ?>
<div class="page-title">
    <h1><?php echo Mage::helper('webformat_viewedproducts')->__('Viewed products') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if(count($_items)): ?>
    <table class="data-table" id="my-viewed-product-table">
        <col/>
        <col width="150"/>
        <col width="150"/>
        <col width="1"/>
        <thead>
            <tr>
                <th><?php echo Mage::helper('webformat_viewedproducts')->__('Product') ?></th>
                <th><?php echo Mage::helper('webformat_viewedproducts')->__('First visited at') ?></th>
                <th><?php echo Mage::helper('webformat_viewedproducts')->__('Last visited at') ?></th>
                <th><?php echo Mage::helper('webformat_viewedproducts')->__('Visit count') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($_items as $_item): ?>
                <tr>
                    <td><?php echo $this->renderProductLink($_item->getProductId()); ?></td>
                    <td><?php echo $this->formatDate($_item->getFirstVisitedAt(), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT, true); ?></td>
                    <td><?php echo $this->formatDate($_item->getLastVisitedAt(), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT, true); ?></td>
                    <td><?php echo $_item->getVisitCount(); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-downloadable-products-table')</script>
<?php else: ?>
    <p><?php echo Mage::helper('webformat_viewedproducts')->__('You have not seen any product yet.'); ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
